/**
 * Dignity-score golden: the TS port (weighted essential dignities) must
 * reproduce the Python reference. Both run the SAME inputs (from
 * dignity-golden.json, generated by python/export_dignity_golden.py). A closing
 * block re-asserts a few defining facts (the Lilly weights, a term boundary, an
 * almuten contest), independent of the golden.
 */
import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { Engine } from "../src/chart.js";
import { loadNodeData } from "../src/node-loader.js";
import { dignityScore, almuten, termRuler, PLANETS, type Sect } from "../src/dignity-score.js";

const here = dirname(fileURLToPath(import.meta.url));
const G = JSON.parse(readFileSync(join(here, "../../test/dignity-golden.json"), "utf8"));
const data = loadNodeData(join(here, "../../data"), "embedded", "full");
const eng = new Engine(data);

// eslint-disable-next-line @typescript-eslint/no-explicit-any
function compute(spec: any): any {
  switch (spec.type) {
    case "score":
      return dignityScore(spec.planet, spec.lon, spec.sect as Sect);
    case "almuten":
      return almuten(spec.lon, spec.sect as Sect);
    case "at": {
      const n = spec.natal as number[];
      const c = eng.chart(n[0], n[1], n[2], n[3], n[4], 0, spec.lat, spec.lon, "placidus");
      const out: Record<string, unknown> = {};
      for (const p of PLANETS) out[p] = dignityScore(p, c.bodies[p]!.lon, spec.sect as Sect);
      return out;
    }
    default:
      throw new Error(`unknown dignity type ${spec.type}`);
  }
}

let checks = 0;
let failures = 0;

// eslint-disable-next-line @typescript-eslint/no-explicit-any
function deepCmp(id: string, got: any, want: any): void {
  if (want !== null && typeof want === "object") {
    if (got === null || typeof got !== "object") {
      checks++; failures++; console.error(`FAIL ${id}: ${JSON.stringify(got)} vs object`);
      return;
    }
    for (const k of Object.keys(want)) deepCmp(`${id}.${k}`, got[k], want[k]);
    for (const k of Object.keys(got)) if (!(k in want)) { checks++; failures++; console.error(`FAIL ${id}.${k}: extra`); }
  } else {
    checks++;
    if (got !== want) { failures++; console.error(`FAIL ${id}: ${JSON.stringify(got)} vs ${JSON.stringify(want)}`); }
  }
}

// eslint-disable-next-line @typescript-eslint/no-explicit-any
for (const c of G.cases as any[]) deepCmp(c.id, compute(c.spec), c.result);

// --- oracle: defining facts, independent of the golden ---
const fail = (m: string) => { checks++; failures++; console.error(`FAIL ${m}`); };
const ok = () => { checks++; };
{
  // Sun ruling Leo by day: rulership 5 + fire-day triplicity 3 = 8
  const s = dignityScore("sun", 135, "day");
  s.rulership === 5 && s.triplicity === 3 && s.total === 8 ? ok() : fail("sun in Leo by day");

  // Saturn in Aries is in its fall and peregrine
  const sat = dignityScore("saturn", 5, "day");
  sat.fall === -4 && sat.peregrine ? ok() : fail("saturn fall in Aries");

  // Egyptian term boundary: 22 Aries is the Mars term (Mercury ends at 20)
  termRuler(0, 22) === "mars" ? ok() : fail("Aries term boundary");

  // almuten of 5 Aries by day is the Sun (exaltation 4 + triplicity 3 = 7 > Mars 6)
  almuten(5, "day").planet === "sun" ? ok() : fail("almuten 5 Aries");

  // sect flips the triplicity ruler: water by night is Mars, not Venus
  dignityScore("mars", 100, "night").triplicity === 3
    && dignityScore("venus", 100, "night").triplicity === 0 ? ok() : fail("night triplicity");
}

console.log(`\n${checks} checks, ${failures} failures`);
process.exit(failures ? 1 : 0);
