/**
 * Electional golden: the TS port of the electional primitives must reproduce
 * the Python reference's results. Both run the SAME specs (from
 * electional-golden.json, generated by python/export_electional_golden.py) on
 * the same VSOP tier. Numbers compared with tolerance; strings, booleans, and
 * structure must match exactly.
 */
import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { julianDay } from "../src/core.js";
import { Engine } from "../src/chart.js";
import { loadNodeData } from "../src/node-loader.js";
import * as E from "../src/electional.js";

const here = dirname(fileURLToPath(import.meta.url));
const G = JSON.parse(readFileSync(join(here, "../../test/electional-golden.json"), "utf8"));
const data = loadNodeData(join(here, "../../data"), "embedded", "full");
const eng = new Engine(data);

function jd(date: number[]): number {
  return julianDay(date[0], date[1], date[2], date[3] ?? 0, date[4] ?? 0, date[5] ?? 0);
}

// eslint-disable-next-line @typescript-eslint/no-explicit-any
function compute(spec: any): any {
  switch (spec.type) {
    case "aspect_phase":
      return E.aspectPhase(spec.lon_a, spec.speed_a, spec.lon_b, spec.speed_b, spec.aspect);
    case "aspect_between":
      return E.aspectBetween(eng, spec.a, spec.b, jd(spec.jd));
    case "solar":
      return {
        elongation: E.solarElongation(eng, spec.body, jd(spec.jd)),
        phase: E.solarPhase(eng, spec.body, jd(spec.jd)),
      };
    case "phour": {
      const ph = E.planetaryHour(eng, jd(spec.jd), spec.lat, spec.lon);
      if (ph === null) return null;
      return {
        ruler: ph.ruler, kind: ph.kind, hour: ph.hour,
        day_ruler: ph.dayRuler, start: ph.start, end: ph.end,
      };
    }
    case "voc": {
      const v = E.voidOfCourse(eng, jd(spec.jd));
      return {
        is_void: v.isVoid, sign: v.sign,
        sign_exit: v.signExit, next_aspect: v.nextAspect,
      };
    }
    case "house": {
      const h = E.houseOf(spec.lon, spec.cusps);
      return { house: h, angularity: E.angularity(h) };
    }
    default: throw new Error(`unknown electional type ${spec.type}`);
  }
}

let checks = 0;
let failures = 0;
let worst = 0;
const TOL = 1e-6;

// eslint-disable-next-line @typescript-eslint/no-explicit-any
function leaf(id: string, got: any, want: any): void {
  checks++;
  if (typeof want === "number") {
    const d = Math.abs(got - want);
    if (d > worst) worst = d;
    if (typeof got !== "number" || d > TOL) {
      failures++; console.error(`FAIL ${id}: ${got} vs ${want} (diff ${d})`);
    }
  } else if (got !== want) {
    failures++;
    console.error(`FAIL ${id}: ${JSON.stringify(got)} vs ${JSON.stringify(want)}`);
  }
}

// eslint-disable-next-line @typescript-eslint/no-explicit-any
function deepCmp(id: string, got: any, want: any): void {
  if (Array.isArray(want)) {
    if (!Array.isArray(got) || got.length !== want.length) {
      checks++; failures++;
      console.error(`FAIL ${id}: length ${got?.length} vs ${want.length}`);
      return;
    }
    for (let i = 0; i < want.length; i++) deepCmp(`${id}[${i}]`, got[i], want[i]);
  } else if (want !== null && typeof want === "object") {
    if (got === null || typeof got !== "object") {
      checks++; failures++;
      console.error(`FAIL ${id}: ${JSON.stringify(got)} vs object`);
      return;
    }
    for (const k of Object.keys(want)) deepCmp(`${id}.${k}`, got[k], want[k]);
  } else {
    leaf(id, got, want);
  }
}

// eslint-disable-next-line @typescript-eslint/no-explicit-any
for (const c of G.cases as any[]) deepCmp(c.id, compute(c.spec), c.result);

console.log(`\n${checks} checks, ${failures} failures`);
console.log(`worst numeric diff: ${worst.toExponential(2)}`);
process.exit(failures ? 1 : 0);
