/**
 * Firdaria golden: the TS port must reproduce the Python reference. Both run the
 * SAME specs (from firdaria-golden.json, generated by
 * python/export_firdaria_golden.py). Numbers compared with tolerance; strings
 * and structure must match exactly. A closing block checks implementation-
 * independent invariants: the nine periods total 75 years, and each planetary
 * period's seven sub-periods tile it exactly and begin with its own lord.
 */
import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { julianDay } from "../src/core.js";
import { Engine } from "../src/chart.js";
import { loadNodeData } from "../src/node-loader.js";
import { TROPICAL_YEAR } from "../src/derived.js";
import * as F from "../src/firdaria.js";

const here = dirname(fileURLToPath(import.meta.url));
const G = JSON.parse(readFileSync(join(here, "../../test/firdaria-golden.json"), "utf8"));
const data = loadNodeData(join(here, "../../data"), "embedded", "full");
const eng = new Engine(data);

function jd(date: number[]): number {
  return julianDay(date[0], date[1], date[2], date[3] ?? 0, date[4] ?? 0, date[5] ?? 0);
}

// eslint-disable-next-line @typescript-eslint/no-explicit-any
function compute(spec: any): any {
  switch (spec.type) {
    case "sequence": return F.firdariaSequence(spec.day);
    case "timeline": return F.firdaria(spec.day, jd(spec.natal));
    case "active": return F.firdariaActive(spec.day, jd(spec.natal), jd(spec.target));
    case "at": return F.firdariaAt(eng, jd(spec.natal), jd(spec.target), spec.lat, spec.lon);
    default: throw new Error(`unknown firdaria type ${spec.type}`);
  }
}

let checks = 0;
let failures = 0;
let worst = 0;
const TOL = 1e-6;

// eslint-disable-next-line @typescript-eslint/no-explicit-any
function leaf(id: string, got: any, want: any): void {
  checks++;
  if (typeof want === "number") {
    const d = Math.abs(got - want);
    if (d > worst) worst = d;
    if (typeof got !== "number" || d > TOL) {
      failures++; console.error(`FAIL ${id}: ${got} vs ${want} (diff ${d})`);
    }
  } else if (got !== want) {
    failures++;
    console.error(`FAIL ${id}: ${JSON.stringify(got)} vs ${JSON.stringify(want)}`);
  }
}

// eslint-disable-next-line @typescript-eslint/no-explicit-any
function deepCmp(id: string, got: any, want: any): void {
  if (want !== null && typeof want === "object") {
    if (got === null || typeof got !== "object") {
      checks++; failures++;
      console.error(`FAIL ${id}: ${JSON.stringify(got)} vs object`);
      return;
    }
    for (const k of Object.keys(want)) deepCmp(`${id}.${k}`, got[k], want[k]);
  } else {
    leaf(id, got, want);
  }
}

// eslint-disable-next-line @typescript-eslint/no-explicit-any
for (const c of G.cases as any[]) deepCmp(c.id, compute(c.spec), c.result);

// Invariants, independent of the golden: 75-year total span, and each planetary
// period's seven sub-periods tile it exactly and begin with its own lord.
{
  const natal = jd([1990, 6, 10, 14, 30]);
  for (const day of [true, false]) {
    const tl = F.firdaria(day, natal);
    checks++;
    const span = (tl[tl.length - 1].end - natal) / TROPICAL_YEAR;
    if (Math.abs(span - 75) > 1e-6) {
      failures++; console.error(`FAIL invariant: ${day ? "day" : "night"} total ${span} != 75y`);
    }
    for (const m of tl) {
      if (m.sub.length === 0) continue; // node periods have no sub-periods
      checks++;
      // tolerance is generous against fp accumulation (7 adds of span/7 vs
      // span ~ 1e-9 days); a wrong period number would be off by whole days.
      const tiles = Math.abs(m.sub[0].start - m.start) < 1e-6
        && Math.abs(m.sub[m.sub.length - 1].end - m.end) < 1e-6
        && m.sub.length === 7 && m.sub[0].lord === m.lord;
      if (!tiles) {
        failures++; console.error(`FAIL invariant: ${m.lord} sub-periods do not tile`);
      }
    }
  }
}

console.log(`\n${checks} checks, ${failures} failures`);
console.log(`worst numeric diff: ${worst.toExponential(2)}`);
process.exit(failures ? 1 : 0);
