/**
 * Lots golden: the TS port of the Hellenistic lots must reproduce the Python
 * reference. Both run the SAME specs (from lots-golden.json, generated by
 * python/export_lots_golden.py) on the same VSOP tier. Numbers compared with
 * tolerance; booleans and structure must match exactly. A closing invariant
 * check asserts Fortune and Spirit are symmetric about the Ascendant -- a
 * mathematical property independent of either implementation, so it catches a
 * sect/formula flip that both ports might share.
 */
import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { julianDay } from "../src/core.js";
import { mod } from "../src/core.js";
import { Engine } from "../src/chart.js";
import { loadNodeData } from "../src/node-loader.js";
import * as L from "../src/lots.js";

const here = dirname(fileURLToPath(import.meta.url));
const G = JSON.parse(readFileSync(join(here, "../../test/lots-golden.json"), "utf8"));
const data = loadNodeData(join(here, "../../data"), "embedded", "full");
const eng = new Engine(data);

function jd(date: number[]): number {
  return julianDay(date[0], date[1], date[2], date[3] ?? 0, date[4] ?? 0, date[5] ?? 0);
}

// eslint-disable-next-line @typescript-eslint/no-explicit-any
function compute(spec: any): any {
  switch (spec.type) {
    case "formula":
      return L.hermeticLots(spec.asc, spec.day, spec.sun, spec.moon, spec.mercury,
        spec.venus, spec.mars, spec.jupiter, spec.saturn);
    case "chart":
      return L.lots(eng, jd(spec.jd), spec.lat, spec.lon, spec.zodiac ?? "tropical");
    default: throw new Error(`unknown lots type ${spec.type}`);
  }
}

let checks = 0;
let failures = 0;
let worst = 0;
const TOL = 1e-6;

// eslint-disable-next-line @typescript-eslint/no-explicit-any
function leaf(id: string, got: any, want: any): void {
  checks++;
  if (typeof want === "number") {
    const d = Math.abs(got - want);
    if (d > worst) worst = d;
    if (typeof got !== "number" || d > TOL) {
      failures++; console.error(`FAIL ${id}: ${got} vs ${want} (diff ${d})`);
    }
  } else if (got !== want) {
    failures++;
    console.error(`FAIL ${id}: ${JSON.stringify(got)} vs ${JSON.stringify(want)}`);
  }
}

// eslint-disable-next-line @typescript-eslint/no-explicit-any
function deepCmp(id: string, got: any, want: any): void {
  if (want !== null && typeof want === "object") {
    if (got === null || typeof got !== "object") {
      checks++; failures++;
      console.error(`FAIL ${id}: ${JSON.stringify(got)} vs object`);
      return;
    }
    for (const k of Object.keys(want)) deepCmp(`${id}.${k}`, got[k], want[k]);
  } else {
    leaf(id, got, want);
  }
}

// eslint-disable-next-line @typescript-eslint/no-explicit-any
for (const c of G.cases as any[]) deepCmp(c.id, compute(c.spec), c.result);

// Invariant (implementation-independent): for every chart case, Fortune and
// Spirit are symmetric about the Ascendant, so (fortune + spirit) == 2*asc.
// eslint-disable-next-line @typescript-eslint/no-explicit-any
for (const c of G.cases as any[]) {
  if (c.spec.type !== "chart") continue;
  const asc = eng.chartAt(jd(c.spec.jd), c.spec.lat, c.spec.lon,
    { zodiac: c.spec.zodiac ?? "tropical" }).angles.asc;
  const sym = mod(c.result.fortune + c.result.spirit - 2 * asc, 360);
  const off = Math.min(sym, 360 - sym);
  checks++;
  if (off > 1e-6) {
    failures++;
    console.error(`FAIL ${c.id}: fortune+spirit not symmetric about asc (off ${off})`);
  }
}

console.log(`\n${checks} checks, ${failures} failures`);
console.log(`worst numeric diff: ${worst.toExponential(2)}`);
process.exit(failures ? 1 : 0);
