/**
 * Parans golden: the TS port (co-angular bodies) must reproduce the Python
 * reference. Both run the SAME (date, latitude) inputs from parans-golden.json
 * (generated by python/export_parans_golden.py). A closing block re-asserts the
 * defining geometry, independent of the golden.
 */
import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { julianDay } from "../src/core.js";
import { riseSet } from "../src/events.js";
import { Engine } from "../src/chart.js";
import { loadNodeData } from "../src/node-loader.js";
import { parans, starParans, starAngleTimes } from "../src/parans.js";
import { gast } from "../src/houses.js";
import { DEG, mod } from "../src/core.js";

const here = dirname(fileURLToPath(import.meta.url));
const G = JSON.parse(readFileSync(join(here, "../../test/parans-golden.json"), "utf8"));
const data = loadNodeData(join(here, "../../data"), "embedded", "full");
const eng = new Engine(data);

let checks = 0;
let failures = 0;

// eslint-disable-next-line @typescript-eslint/no-explicit-any
function deepCmp(id: string, got: any, want: any): void {
  if (want !== null && typeof want === "object") {
    if (got === null || typeof got !== "object") {
      checks++; failures++; console.error(`FAIL ${id}: ${JSON.stringify(got)} vs object`);
      return;
    }
    for (const k of Object.keys(want)) deepCmp(`${id}.${k}`, got[k], want[k]);
    for (const k of Object.keys(got)) if (!(k in want)) { checks++; failures++; console.error(`FAIL ${id}.${k}: extra`); }
  } else {
    checks++;
    const same = typeof want === "number" && typeof got === "number"
      ? Math.abs(got - want) <= 1e-5
      : got === want;
    if (!same) { failures++; console.error(`FAIL ${id}: ${JSON.stringify(got)} vs ${JSON.stringify(want)}`); }
  }
}

// eslint-disable-next-line @typescript-eslint/no-explicit-any
for (const c of G.cases as any[]) {
  const got = c.spec.type === "star"
    ? starParans(eng, c.spec.jd, c.spec.lat, c.spec.stars, undefined, c.spec.tolerance_min)
    : parans(eng, c.spec.jd, c.spec.lat, undefined, c.spec.tolerance_min);
  deepCmp(c.id, got, c.result);
}

// --- oracle: each reported paran's bodies really are on their angles together ---
const fail = (m: string) => { checks++; failures++; console.error(`FAIL ${m}`); };
const ok = () => { checks++; };
{
  const jd = julianDay(1990, 6, 10);
  const ps = parans(eng, jd, 27.95, undefined, 30);
  ps.length > 0 ? ok() : fail("parans: found pairs at Tampa");
  // re-derive: each body's reported angle time matches riseSet, and the gap holds
  let consistent = true;
  for (const p of ps) {
    const ta = riseSet(eng, p.a, jd, 27.95, 0, p.a_angle as "rise");
    const tb = riseSet(eng, p.b, jd, 27.95, 0, p.b_angle as "rise");
    if (ta === null || tb === null) { consistent = false; break; }
    if (Math.abs(Math.abs(ta - tb) * 1440 - p.gap_min) > 1e-3) consistent = false;
    if (Math.abs(ta - tb) * 1440 > 30 + 1e-6) consistent = false; // within tolerance
  }
  consistent ? ok() : fail("parans: reported gaps match rise/set times and the tolerance");
}

// --- oracle: a star's upper-meridian time is when sidereal time equals its RA ---
{
  const jd = julianDay(1990, 6, 10);
  const at = starAngleTimes(eng, "Regulus", jd, 27.95);
  const ra = mod(eng.fixedStar("Regulus", jd).ra * DEG, 2 * Math.PI);
  Math.abs(mod(gast(eng.data, at.mtransit) - ra + Math.PI, 2 * Math.PI) - Math.PI) < 1e-6
    ? ok() : fail("star mtransit: sidereal time equals the star's RA");
  starParans(eng, jd, 27.95, ["Regulus", "Aldebaran", "Spica", "Sirius"]).length > 0
    ? ok() : fail("star parans: found star-to-body pairs at Tampa");
}

console.log(`\n${checks} checks, ${failures} failures`);
process.exit(failures ? 1 : 0);
