/**
 * Patterns golden: the TS port (aspect configurations) must reproduce the Python
 * reference. Both run the SAME inputs (from patterns-golden.json, generated by
 * python/export_patterns_golden.py). A closing block re-asserts the defining rule
 * of each configuration and the sub-pattern suppression, an oracle independent of
 * the golden.
 */
import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { Engine } from "../src/chart.js";
import { loadNodeData } from "../src/node-loader.js";
import { detectPatterns, detectPatternsIn, type PatternBody } from "../src/patterns.js";

const here = dirname(fileURLToPath(import.meta.url));
const G = JSON.parse(readFileSync(join(here, "../../test/patterns-golden.json"), "utf8"));
const data = loadNodeData(join(here, "../../data"), "embedded", "full");
const eng = new Engine(data);

// eslint-disable-next-line @typescript-eslint/no-explicit-any
function compute(spec: any): any {
  switch (spec.type) {
    case "detect":
      return detectPatternsIn(spec.bodies as Record<string, PatternBody>);
    case "at": {
      const n = spec.natal as number[];
      const c = eng.chart(n[0], n[1], n[2], n[3], n[4], 0, spec.lat, spec.lon, "placidus");
      return detectPatterns(c);
    }
    default:
      throw new Error(`unknown patterns type ${spec.type}`);
  }
}

let checks = 0;
let failures = 0;

// eslint-disable-next-line @typescript-eslint/no-explicit-any
function deepCmp(id: string, got: any, want: any): void {
  if (want !== null && typeof want === "object") {
    if (got === null || typeof got !== "object") {
      checks++; failures++; console.error(`FAIL ${id}: ${JSON.stringify(got)} vs object`);
      return;
    }
    for (const k of Object.keys(want)) deepCmp(`${id}.${k}`, got[k], want[k]);
    for (const k of Object.keys(got)) if (!(k in want)) { checks++; failures++; console.error(`FAIL ${id}.${k}: extra`); }
  } else {
    checks++;
    const same = typeof want === "number" && typeof got === "number"
      ? Math.abs(got - want) <= 1e-9
      : got === want;
    if (!same) { failures++; console.error(`FAIL ${id}: ${JSON.stringify(got)} vs ${JSON.stringify(want)}`); }
  }
}

// eslint-disable-next-line @typescript-eslint/no-explicit-any
for (const c of G.cases as any[]) deepCmp(c.id, compute(c.spec), c.result);

// --- oracle: each configuration's defining geometry + sub-pattern suppression ---
const fail = (m: string) => { checks++; failures++; console.error(`FAIL ${m}`); };
const ok = () => { checks++; };
const kinds = (b: Record<string, PatternBody>) => detectPatternsIn(b).map((p) => p.kind);
{
  // grand trine: three bodies 120 apart
  kinds({ sun: { lon: 0 }, moon: { lon: 120 }, mars: { lon: 240 } }).includes("grand_trine")
    ? ok() : fail("grand trine not detected");

  // grand cross suppresses the T-squares it contains
  const cross = kinds({ sun: { lon: 0 }, moon: { lon: 180 }, mars: { lon: 90 }, venus: { lon: 270 } });
  cross.includes("grand_cross") && !cross.includes("t_square")
    ? ok() : fail("grand cross / T-square suppression");

  // kite suppresses its grand trine
  const kite = kinds({ sun: { lon: 0 }, moon: { lon: 120 }, mars: { lon: 240 }, venus: { lon: 180 } });
  kite.includes("kite") && !kite.includes("grand_trine")
    ? ok() : fail("kite / grand trine suppression");

  // yod: a sextile both ends quincunx an apex
  kinds({ sun: { lon: 0 }, moon: { lon: 60 }, saturn: { lon: 210 } }).includes("yod")
    ? ok() : fail("yod not detected");

  // stellium by house only when three share a house
  detectPatternsIn({
    sun: { lon: 5, house: 1 }, moon: { lon: 40, house: 1 }, mercury: { lon: 200, house: 1 },
  }).some((p) => p.kind === "stellium_house" && p.house === 1)
    ? ok() : fail("stellium_house not detected");

  // nodes are excluded by default (a node completing a trine is ignored)
  kinds({ sun: { lon: 0 }, moon: { lon: 120 }, true_node: { lon: 240 } }).includes("grand_trine")
    ? fail("a node was treated as aspectable") : ok();
}

console.log(`\n${checks} checks, ${failures} failures`);
process.exit(failures ? 1 : 0);
