/**
 * Query-engine golden: the TS port of when() must reproduce the Python
 * reference's intervals. Both run the SAME specs (from query-golden.json,
 * generated by python/export_query_golden.py) on the same VSOP tier, so the
 * bisected boundaries match to well under the tolerance.
 */
import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { Engine } from "../src/chart.js";
import { loadNodeData } from "../src/node-loader.js";
import {
  when, aspect, inSign, retrograde, notRetrograde, allOf, anyOf, notOf,
  Predicate, Interval,
} from "../src/query.js";

const here = dirname(fileURLToPath(import.meta.url));
const G = JSON.parse(readFileSync(join(here, "../../test/query-golden.json"), "utf8"));
const data = loadNodeData(join(here, "../../data"), "embedded", "full");
const eng = new Engine(data);

// eslint-disable-next-line @typescript-eslint/no-explicit-any
function build(spec: any): Predicate {
  switch (spec.kind) {
    case "aspect": return aspect(spec.body, spec.aspect, spec.target, spec.orb ?? 1.0);
    case "in_sign": return inSign(spec.body, spec.sign);
    case "retrograde": return retrograde(spec.body);
    case "not_retrograde": return notRetrograde(spec.body);
    case "all": return allOf(...spec.of.map(build));
    case "any": return anyOf(...spec.of.map(build));
    case "not": return notOf(build(spec.of));
    default: throw new Error(`unknown spec kind ${spec.kind}`);
  }
}

let checks = 0;
let failures = 0;
let worst = 0;
const TOL = 1e-3; // days (~86 s); boundaries match to ~1e-6 in practice

// eslint-disable-next-line @typescript-eslint/no-explicit-any
for (const c of G.cases as any[]) {
  const got: Interval[] = when(eng, build(c.spec), c.jd0, c.jd1);
  const want: Interval[] = c.intervals;
  checks++;
  if (got.length !== want.length) {
    failures++;
    console.error(`FAIL ${c.id}: got ${got.length} intervals, want ${want.length}`);
    continue;
  }
  for (let i = 0; i < got.length; i++) {
    for (let j = 0; j < 2; j++) {
      checks++;
      const diff = Math.abs(got[i][j] - want[i][j]);
      if (diff > worst) worst = diff;
      if (diff > TOL) {
        failures++;
        console.error(`FAIL ${c.id} interval ${i}[${j}]: diff ${diff} d`);
      }
    }
  }
}

console.log(`\n${checks} checks, ${failures} failures`);
console.log(`worst boundary diff: ${(worst * 86400).toExponential(2)} s`);
process.exit(failures ? 1 : 0);
