/**
 * Rajayoga golden: the TS port (lordship/drishti + raja/dhana yogas) must
 * reproduce the Python reference. Both run the SAME specs (from
 * rajayoga-golden.json, generated by python/export_rajayoga_golden.py). Structure
 * exact. A closing block checks the defining rules directly: the special graha
 * drishti, yogakarakas (Taurus -> Saturn, Aries -> none), a constructed raja
 * yoga, and association symmetry -- oracles independent of the golden.
 */
import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { julianDay } from "../src/core.js";
import { Engine } from "../src/chart.js";
import { loadNodeData } from "../src/node-loader.js";
import * as R from "../src/rajayoga.js";

const here = dirname(fileURLToPath(import.meta.url));
const G = JSON.parse(readFileSync(join(here, "../../test/rajayoga-golden.json"), "utf8"));
const data = loadNodeData(join(here, "../../data"), "embedded", "full");
const eng = new Engine(data);

function jd(date: number[]): number {
  return julianDay(date[0], date[1], date[2], date[3] ?? 0, date[4] ?? 0, date[5] ?? 0);
}

// eslint-disable-next-line @typescript-eslint/no-explicit-any
function compute(spec: any): any {
  switch (spec.type) {
    case "drishti": return { aspects: R.aspectsSign(spec.planet, spec.ps, spec.ts) };
    case "parivartana": return { exchange: R.parivartana(spec.pa, spec.sa, spec.pb, spec.sb) };
    case "assoc": return { via: R.associationType(spec.pa, spec.sa, spec.pb, spec.sb) };
    case "yogakaraka": return { yogakarakas: R.yogakarakas(spec.asc) };
    case "raja": return R.rajaYogas(spec.signs, spec.asc);
    case "dhana": return R.dhanaYogas(spec.signs, spec.asc);
    case "raja_at": return R.rajaYogasAt(eng, jd(spec.natal), spec.lat, spec.lon);
    case "dhana_at": return R.dhanaYogasAt(eng, jd(spec.natal), spec.lat, spec.lon);
    default: throw new Error(`unknown rajayoga type ${spec.type}`);
  }
}

let checks = 0;
let failures = 0;

// eslint-disable-next-line @typescript-eslint/no-explicit-any
function deepCmp(id: string, got: any, want: any): void {
  if (want !== null && typeof want === "object") {
    if (got === null || typeof got !== "object") {
      checks++; failures++; console.error(`FAIL ${id}: ${JSON.stringify(got)} vs object`);
      return;
    }
    for (const k of Object.keys(want)) deepCmp(`${id}.${k}`, got[k], want[k]);
    for (const k of Object.keys(got)) if (!(k in want)) { checks++; failures++; console.error(`FAIL ${id}.${k}: extra`); }
  } else {
    checks++;
    if (got !== want) { failures++; console.error(`FAIL ${id}: ${JSON.stringify(got)} vs ${JSON.stringify(want)}`); }
  }
}

// eslint-disable-next-line @typescript-eslint/no-explicit-any
for (const c of G.cases as any[]) deepCmp(c.id, compute(c.spec), c.result);

// --- oracles, independent of the golden ---
const fail = (m: string) => { checks++; failures++; console.error(`FAIL ${m}`); };
const ok = () => { checks++; };
{
  // special graha drishti (from Aries, sign 0): Mars 4th/8th, Jupiter 5th/9th,
  // Saturn 3rd/10th, every planet the 7th; the Sun has no 4th aspect
  R.aspectsSign("mars", 0, 3) && R.aspectsSign("mars", 0, 7) ? ok() : fail("Mars 4/8 drishti");
  R.aspectsSign("jupiter", 0, 4) && R.aspectsSign("jupiter", 0, 8) ? ok() : fail("Jupiter 5/9 drishti");
  R.aspectsSign("saturn", 0, 2) && R.aspectsSign("saturn", 0, 9) ? ok() : fail("Saturn 3/10 drishti");
  R.aspectsSign("sun", 0, 6) && !R.aspectsSign("sun", 0, 3) ? ok() : fail("Sun only 7th drishti");

  // yogakarakas: Taurus asc -> Saturn; Aries asc -> none
  JSON.stringify(R.yogakarakas(1)) === JSON.stringify(["saturn"]) ? ok() : fail("Taurus yogakaraka");
  R.yogakarakas(0).length === 0 ? ok() : fail("Aries has no yogakaraka");

  // a constructed raja yoga: Aries asc, the 4th lord (Moon) conjunct the 5th
  // lord (Sun) -> kendra/trikona lord association
  const signs = { sun: 3, moon: 3, mars: 0, mercury: 5, jupiter: 8, venus: 6, saturn: 9 };
  const raja = R.rajaYogas(signs, 0);
  raja.some((y) => y.lords.includes("moon") && y.lords.includes("sun") && y.via === "conjunction")
    ? ok() : fail("Moon-Sun raja yoga not detected");

  // association is symmetric
  for (const [a, sa, b, sb] of [["mars", 0, "saturn", 6], ["mars", 1, "venus", 0]] as Array<[string, number, string, number]>) {
    (!!R.associationType(a, sa, b, sb)) === (!!R.associationType(b, sb, a, sa)) ? ok() : fail(`association symmetry ${a}/${b}`);
  }
}

console.log(`\n${checks} checks, ${failures} failures`);
process.exit(failures ? 1 : 0);
