/**
 * Signature golden: the TS port (structural chart signature) must reproduce the
 * Python reference. Both run the SAME inputs (from signature-golden.json,
 * generated by python/export_signature_golden.py). A closing block re-asserts the
 * defining counts, the tie-breaking, and the node exclusion, independent of the
 * golden.
 */
import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { Engine } from "../src/chart.js";
import { loadNodeData } from "../src/node-loader.js";
import { chartSignature, chartSignatureOf, type SignatureBody } from "../src/signature.js";

const here = dirname(fileURLToPath(import.meta.url));
const G = JSON.parse(readFileSync(join(here, "../../test/signature-golden.json"), "utf8"));
const data = loadNodeData(join(here, "../../data"), "embedded", "full");
const eng = new Engine(data);

// eslint-disable-next-line @typescript-eslint/no-explicit-any
function compute(spec: any): any {
  switch (spec.type) {
    case "sig":
      return chartSignatureOf(spec.bodies as Record<string, SignatureBody>, { ascSign: spec.asc_sign ?? null });
    case "at": {
      const n = spec.natal as number[];
      const c = eng.chart(n[0], n[1], n[2], n[3], n[4], 0, spec.lat, spec.lon, "placidus");
      return chartSignature(c);
    }
    default:
      throw new Error(`unknown signature type ${spec.type}`);
  }
}

let checks = 0;
let failures = 0;

// eslint-disable-next-line @typescript-eslint/no-explicit-any
function deepCmp(id: string, got: any, want: any): void {
  if (want !== null && typeof want === "object") {
    if (got === null || typeof got !== "object") {
      checks++; failures++; console.error(`FAIL ${id}: ${JSON.stringify(got)} vs object`);
      return;
    }
    for (const k of Object.keys(want)) deepCmp(`${id}.${k}`, got[k], want[k]);
    for (const k of Object.keys(got)) if (!(k in want)) { checks++; failures++; console.error(`FAIL ${id}.${k}: extra`); }
  } else {
    checks++;
    if (got !== want) { failures++; console.error(`FAIL ${id}: ${JSON.stringify(got)} vs ${JSON.stringify(want)}`); }
  }
}

// eslint-disable-next-line @typescript-eslint/no-explicit-any
for (const c of G.cases as any[]) deepCmp(c.id, compute(c.spec), c.result);

// --- oracle: defining counts, tie-breaking, exclusions ---
const fail = (m: string) => { checks++; failures++; console.error(`FAIL ${m}`); };
const ok = () => { checks++; };
{
  // three bodies in Aries -> fire/cardinal dominate, Aries the dominant sign,
  // Mars the ruler of an Aries Ascendant
  const s = chartSignatureOf(
    { sun: { lon: 5 }, moon: { lon: 15 }, mars: { lon: 25 } }, { ascSign: 0 },
  );
  s.elements.fire === 3 && s.dominant.element === "fire"
    && s.dominant.modality === "cardinal" && s.dominant.sign === "Aries"
    && s.ruler === "mars" ? ok() : fail("aries stellium signature");

  // a four-way element tie resolves to fire (canonical order)
  const tie = chartSignatureOf({
    a: { lon: 5 }, b: { lon: 35 }, c: { lon: 65 }, d: { lon: 95 },
  }, { bodies: ["a", "b", "c", "d"] });
  tie.dominant.element === "fire" ? ok() : fail("element tie not broken canonically");
  // all four signs distinct -> no dominant sign
  tie.dominant.sign === null ? ok() : fail("dominant sign reported for distinct signs");

  // angular houses counted; quadrant + hemisphere bookkeeping
  const ang = chartSignatureOf({
    a: { lon: 5, house: 1 }, b: { lon: 100, house: 4 },
    c: { lon: 200, house: 7 }, d: { lon: 280, house: 10 },
  }, { bodies: ["a", "b", "c", "d"] });
  ang.angularity.angular === 4 && ang.hemispheres.above === 2 ? ok() : fail("angularity counts");

  // nodes are excluded by default
  const noNode = chartSignatureOf({ sun: { lon: 0 }, true_node: { lon: 0 } });
  noNode.bodies.length === 1 && noNode.elements.fire === 1 ? ok() : fail("node not excluded");
}

console.log(`\n${checks} checks, ${failures} failures`);
process.exit(failures ? 1 : 0);
