/**
 * Vargas golden: the TS port (divisional charts) must reproduce the Python
 * reference. Both run the SAME specs (from vargas-golden.json, generated by
 * python/export_vargas_golden.py). Strings and structure exact; numbers with
 * tolerance. A closing block checks textbook varga placements directly, an
 * oracle independent of the golden.
 */
import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { julianDay } from "../src/core.js";
import { Engine } from "../src/chart.js";
import { loadNodeData } from "../src/node-loader.js";
import * as V from "../src/vargas.js";

const here = dirname(fileURLToPath(import.meta.url));
const G = JSON.parse(readFileSync(join(here, "../../test/vargas-golden.json"), "utf8"));
const data = loadNodeData(join(here, "../../data"), "embedded", "full");
const eng = new Engine(data);

function jd(date: number[]): number {
  return julianDay(date[0], date[1], date[2], date[3] ?? 0, date[4] ?? 0, date[5] ?? 0);
}

// eslint-disable-next-line @typescript-eslint/no-explicit-any
function compute(spec: any): any {
  switch (spec.type) {
    case "varga": return V.varga(spec.lon, spec.n);
    case "varga_at": return V.vargaAt(eng, jd(spec.natal), spec.n);
    case "chart": return V.vargaChart(eng, jd(spec.natal), spec.n);
    default: throw new Error(`unknown vargas type ${spec.type}`);
  }
}

let checks = 0;
let failures = 0;
let worst = 0;
const TOL = 1e-6;

// eslint-disable-next-line @typescript-eslint/no-explicit-any
function leaf(id: string, got: any, want: any): void {
  checks++;
  if (typeof want === "number") {
    const d = Math.abs(got - want);
    if (d > worst) worst = d;
    if (typeof got !== "number" || d > TOL) {
      failures++; console.error(`FAIL ${id}: ${got} vs ${want} (diff ${d})`);
    }
  } else if (got !== want) {
    failures++;
    console.error(`FAIL ${id}: ${JSON.stringify(got)} vs ${JSON.stringify(want)}`);
  }
}

// eslint-disable-next-line @typescript-eslint/no-explicit-any
function deepCmp(id: string, got: any, want: any): void {
  if (want !== null && typeof want === "object") {
    if (got === null || typeof got !== "object") {
      checks++; failures++;
      console.error(`FAIL ${id}: ${JSON.stringify(got)} vs object`);
      return;
    }
    for (const k of Object.keys(want)) deepCmp(`${id}.${k}`, got[k], want[k]);
  } else {
    leaf(id, got, want);
  }
}

// eslint-disable-next-line @typescript-eslint/no-explicit-any
for (const c of G.cases as any[]) deepCmp(c.id, compute(c.spec), c.result);

// --- textbook varga placements, independent of the golden ---
const fail = (m: string) => { checks++; failures++; console.error(`FAIL ${m}`); };
const want = (lon: number, n: number, sign: string, id: string) => {
  checks++;
  const got = V.varga(lon, n).sign;
  if (got !== sign) { failures++; console.error(`FAIL ${id}: D${n}(${lon}) = ${got}, expected ${sign}`); }
};
{
  // D9 navamsa: movable sign from itself; Taurus from Capricorn; Aries 9th = Sagittarius
  want(0, 9, "Aries", "nav-aries"); want(30, 9, "Capricorn", "nav-taurus"); want(28, 9, "Sagittarius", "nav-aries9");
  // D3 drekkana: 1st = sign, 2nd = +4 (Leo), 3rd = +8 (Sagittarius)
  want(5, 3, "Aries", "drek1"); want(15, 3, "Leo", "drek2"); want(25, 3, "Sagittarius", "drek3");
  // D10 dasamsa: odd from sign, even from the 9th
  want(1, 10, "Aries", "das-aries"); want(31, 10, "Capricorn", "das-taurus");
  // D12 dwadasamsa: from the sign itself
  want(1, 12, "Aries", "dwad-aries");
  // D1 is always the rasi; division always within 1..n
  for (const lon of [0, 17, 123.4, 359.9]) for (const n of V.VARGA_DIVISIONS) {
    const v = V.varga(lon, n);
    if (n === 1 && v.sign !== v.rasi) fail(`D1(${lon}) sign != rasi`);
    if (v.division < 1 || v.division > n) fail(`D${n}(${lon}) division ${v.division} out of range`);
  }
}

console.log(`\n${checks} checks, ${failures} failures`);
console.log(`worst numeric diff: ${worst.toExponential(2)}`);
process.exit(failures ? 1 : 0);
