/**
 * Yogini dasha golden: the TS port must reproduce the Python reference. Both run
 * the SAME specs (from yogini-golden.json, generated by
 * python/export_yogini_golden.py). Strings and structure exact; numbers with
 * tolerance. A closing block checks implementation-independent facts: the eight
 * yogini years total 36, each period's sub-periods tile it from its own yogini,
 * and Ashwini (nakshatra 0) starts the Bhramari yogini ((1 + 3) mod 8 = 4).
 */
import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { julianDay } from "../src/core.js";
import { Engine } from "../src/chart.js";
import { loadNodeData } from "../src/node-loader.js";
import * as Y from "../src/yogini.js";

const here = dirname(fileURLToPath(import.meta.url));
const G = JSON.parse(readFileSync(join(here, "../../test/yogini-golden.json"), "utf8"));
const data = loadNodeData(join(here, "../../data"), "embedded", "full");
const eng = new Engine(data);

function jd(date: number[]): number {
  return julianDay(date[0], date[1], date[2], date[3] ?? 0, date[4] ?? 0, date[5] ?? 0);
}

// eslint-disable-next-line @typescript-eslint/no-explicit-any
function compute(spec: any): any {
  switch (spec.type) {
    case "start": return { yogini: Y.YOGINIS[Y.startingYogini(spec.nak)] };
    case "dashas": return Y.yoginiDashas(spec.moon_lon, jd(spec.natal), 2);
    case "active": return Y.yoginiActive(spec.moon_lon, jd(spec.natal), jd(spec.target));
    case "at": return Y.yoginiAt(eng, jd(spec.natal), jd(spec.target));
    default: throw new Error(`unknown yogini type ${spec.type}`);
  }
}

let checks = 0;
let failures = 0;
let worst = 0;
const TOL = 1e-6;

// eslint-disable-next-line @typescript-eslint/no-explicit-any
function leaf(id: string, got: any, want: any): void {
  checks++;
  if (typeof want === "number") {
    const d = Math.abs(got - want);
    if (d > worst) worst = d;
    if (typeof got !== "number" || d > TOL) {
      failures++; console.error(`FAIL ${id}: ${got} vs ${want} (diff ${d})`);
    }
  } else if (got !== want) {
    failures++;
    console.error(`FAIL ${id}: ${JSON.stringify(got)} vs ${JSON.stringify(want)}`);
  }
}

// eslint-disable-next-line @typescript-eslint/no-explicit-any
function deepCmp(id: string, got: any, want: any): void {
  if (want !== null && typeof want === "object") {
    if (got === null || typeof got !== "object") {
      checks++; failures++;
      console.error(`FAIL ${id}: ${JSON.stringify(got)} vs object`);
      return;
    }
    for (const k of Object.keys(want)) deepCmp(`${id}.${k}`, got[k], want[k]);
  } else {
    leaf(id, got, want);
  }
}

// eslint-disable-next-line @typescript-eslint/no-explicit-any
for (const c of G.cases as any[]) deepCmp(c.id, compute(c.spec), c.result);

// --- invariants, independent of the golden ---
const fail = (m: string) => { checks++; failures++; console.error(`FAIL ${m}`); };
const ok = () => { checks++; };
{
  const total = Y.YOGINI_YEARS.reduce((a, b) => a + b, 0);
  if (total !== 36) fail(`yogini years total ${total} != 36`); else ok();

  if (Y.YOGINIS[Y.startingYogini(0)] !== "Bhramari") fail(`Ashwini start ${Y.YOGINIS[Y.startingYogini(0)]}`); else ok();

  const tl = Y.yoginiDashas(45, jd([1990, 6, 10, 14, 30]), 2);
  for (const m of tl.dashas) {
    if (m.sub.length !== 8) { fail(`${m.yogini}: ${m.sub.length} sub-periods`); continue; }
    const tiles = Math.abs(m.sub[0].start - m.start) < 1e-6
      && Math.abs(m.sub[7].end - m.end) < 1e-6
      && m.sub[0].yogini === m.yogini;
    if (!tiles) fail(`${m.yogini}: sub-periods do not tile`); else ok();
  }
}

console.log(`\n${checks} checks, ${failures} failures`);
console.log(`worst numeric diff: ${worst.toExponential(2)}`);
process.exit(failures ? 1 : 0);
