/**
 * Derive accuracy.json `counts` from source and verify (or update) the JSON file.
 * Run after changing MCP tools, house systems, default bodies, or ayanamsas.
 *
 *   node scripts/sync-facts.mjs          # check only; exit 1 on drift
 *   node scripts/sync-facts.mjs --write  # update packages/caelus/accuracy.json
 */
import { readFileSync, writeFileSync } from "node:fs";
import { execFileSync } from "node:child_process";

const ROOT = new URL("..", import.meta.url).pathname;
const rel = (p) => ROOT + p;

const ACCURACY_PATH = rel("packages/caelus/accuracy.json");
const ANCHORS_PATH = rel("apps/web/lib/facts-anchors.generated.ts");
const MCP_SERVER = rel("packages/caelus-mcp/src/server.ts");
const CHART_TS = rel("packages/caelus/src/chart.ts");
const CORE_TS = rel("packages/caelus/src/core.ts");
const WRITE = process.argv.includes("--write");

const PROSE_COUNT = {
  7: "seven",
  12: "twelve",
  13: "thirteen",
  29: "twenty-nine",
  31: "thirty-one",
};

function formatGoldenChecks(n) {
  return n.toLocaleString("en-US");
}

function formatWorstNano(n) {
  return String(Number(n.toFixed(2)));
}

function formatCountProse(n) {
  return PROSE_COUNT[n] ?? String(n);
}

function titleCase(word) {
  return word.charAt(0).toUpperCase() + word.slice(1);
}

function countRegisterTools(src) {
  const names = [...src.matchAll(/server\.registerTool\(\s*"([^"]+)"/g)].map((m) => m[1]);
  if (!names.length) throw new Error(`no registerTool calls found in ${MCP_SERVER}`);
  return names.length;
}

function countQuotedIds(src, exportName) {
  const block = src.match(new RegExp(`export const ${exportName}[^=]*=\\s*\\[([^\\]]+)\\]`, "s"));
  if (!block) throw new Error(`could not parse ${exportName} in ${CHART_TS}`);
  const ids = [...block[1].matchAll(/"([^"]+)"/g)].map((m) => m[1]);
  if (!ids.length) throw new Error(`${exportName} parsed empty`);
  return ids.length;
}

function countRecordKeys(src, constName) {
  const block = src.match(new RegExp(`(?:export )?const ${constName}[^=]*=\\s*\\{([^}]*)\\}`, "s"));
  if (!block) throw new Error(`could not parse ${constName}`);
  const keys = [...block[1].matchAll(/^\s*(\w+)\s*:/gm)].map((m) => m[1]);
  if (!keys.length) throw new Error(`${constName} parsed empty`);
  return keys.length;
}

function deriveCounts() {
  const mcpSrc = readFileSync(MCP_SERVER, "utf8");
  const chartSrc = readFileSync(CHART_TS, "utf8");
  const coreSrc = readFileSync(CORE_TS, "utf8");

  const meanAyanamsas = countRecordKeys(coreSrc, "AYANAMSA_J2000");
  const starAyanamsas = countRecordKeys(chartSrc, "STAR_AYANAMSAS");

  return {
    mcp_tools: countRegisterTools(mcpSrc),
    house_systems: countQuotedIds(chartSrc, "HOUSE_SYSTEMS"),
    default_bodies: countQuotedIds(chartSrc, "BODIES"),
    sidereal_ayanamsas: meanAyanamsas + starAyanamsas,
  };
}

function ensureConformanceStats() {
  const statsPath = process.env.CAELUS_STATS_OUT || rel("conformance-stats.json");
  if (statsPath.endsWith("conformance-stats.json")) {
    const golden = rel("packages/caelus/dist/test/golden.test.js");
    try {
      readFileSync(statsPath, "utf8");
    } catch {
      execFileSync("node", [golden], {
        env: { ...process.env, CAELUS_STATS_OUT: statsPath },
        stdio: "inherit",
      });
    }
  }
}

function loadConformanceStats() {
  const statsPath = process.env.CAELUS_STATS_OUT || rel("conformance-stats.json");
  return JSON.parse(readFileSync(statsPath, "utf8"));
}

function buildAnchors(counts, stats) {
  const golden = formatGoldenChecks(stats.checks);
  const worst = formatWorstNano(stats.worst.nano_arcsec);
  const mcpWord = formatCountProse(counts.mcp_tools);
  const houseWord = formatCountProse(counts.house_systems);
  const siderealWord = formatCountProse(counts.sidereal_ayanamsas);

  return {
    GOLDEN_CHECK_CLAIMS: `${golden}, ${golden} golden checks, ${golden} fixtures`,
    WORST_NANO_CLAIMS: `${worst} nano-arcsecond`,
    MCP_TOOL_CLAIMS:
      `${counts.mcp_tools} chart tools, ${counts.mcp_tools} MCP tools, MCP tools (${counts.mcp_tools}), ` +
      `${mcpWord} chart tools, ${titleCase(mcpWord)} chart tools, ${mcpWord} tools`,
    HOUSE_SYSTEM_CLAIMS:
      `${counts.house_systems} house systems, ${counts.house_systems} systems, ` +
      `${houseWord} house systems, ${titleCase(houseWord)} house systems`,
    SIDEREAL_CLAIMS:
      `${counts.sidereal_ayanamsas} sidereal, ${counts.sidereal_ayanamsas} ayanamsas, ` +
      `${siderealWord} sidereal, ${siderealWord} ayanamsas`,
    DEFAULT_BODY_CLAIMS: `${counts.default_bodies} bodies, Thirteen in the default`,
  };
}

function renderAnchorsFile(anchors) {
  const lines = [
    "/** Generated by scripts/sync-facts.mjs — do not edit by hand. */",
    ...Object.entries(anchors).map(
      ([name, value]) => `export const ${name} = ${JSON.stringify(value)};`,
    ),
    "",
  ];
  return lines.join("\n");
}

ensureConformanceStats();

const accuracy = JSON.parse(readFileSync(ACCURACY_PATH, "utf8"));
const derived = deriveCounts();
const stored = accuracy.counts ?? {};
const countMismatches = Object.entries(derived).filter(([k, v]) => stored[k] !== v);
const counts = { ...stored, ...derived };
const stats = loadConformanceStats();
const anchors = buildAnchors(counts, stats);
const anchorsRendered = renderAnchorsFile(anchors);
let failed = false;

if (countMismatches.length) {
  const detail = countMismatches.map(([k, v]) => `  ${k}: stored ${stored[k]} → derived ${v}`).join("\n");
  if (WRITE) {
    accuracy.counts = counts;
    writeFileSync(ACCURACY_PATH, JSON.stringify(accuracy, null, 2) + "\n");
    console.log(`sync-facts: updated accuracy.json counts:\n${detail}`);
  } else {
    console.error(`sync-facts: accuracy.json counts drift:\n${detail}\nRun: node scripts/sync-facts.mjs --write`);
    failed = true;
  }
}

let anchorsOnDisk = "";
try {
  anchorsOnDisk = readFileSync(ANCHORS_PATH, "utf8");
} catch {
  if (!WRITE) {
    console.error(`sync-facts: missing ${ANCHORS_PATH}\nRun: node scripts/sync-facts.mjs --write`);
    failed = true;
  }
}

if (anchorsOnDisk !== anchorsRendered) {
  if (WRITE) {
    writeFileSync(ANCHORS_PATH, anchorsRendered);
    console.log("sync-facts: updated facts-anchors.generated.ts");
  } else {
    console.error(`sync-facts: facts-anchors.generated.ts is stale\nRun: node scripts/sync-facts.mjs --write`);
    failed = true;
  }
}

if (failed) process.exit(1);

console.log(
  `sync-facts: OK (golden=${stats.checks}, worst=${formatWorstNano(stats.worst.nano_arcsec)} nano, ` +
    `mcp=${derived.mcp_tools}, houses=${derived.house_systems}, bodies=${derived.default_bodies}, ayanamsas=${derived.sidereal_ayanamsas})`,
);
